# Generated by Django 4.0.6 on 2022-07-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="body",
            field=models.CharField(max_length=255),
        ),
    ]
