# Generated by Django 4.0.6 on 2022-08-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_articlebookmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=400, null=True, unique=True
            ),
        ),
    ]
