# Generated by Django 4.0.6 on 2022-07-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_article_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="favourited",
            field=models.BooleanField(null=True),
        ),
    ]
