# Generated by Django 4.0.6 on 2022-07-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_article_favourited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_id",
            field=models.UUIDField(
                default="5545d65c67a74998b96c1cf1152bcd41",
                editable=False,
                unique=True,
            ),
        ),
    ]
