# Generated by Django 4.0.6 on 2022-07-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_alter_article_article_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_id",
            field=models.UUIDField(
                default="fe6e746ba821466480a12f0622f386f9",
                editable=False,
                unique=True,
            ),
        ),
    ]
