# Generated by Django 4.0.6 on 2022-08-04 06:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_alter_articlebookmark_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlebookmark",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="articlebookmark",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
