# Generated by Django 4.0.6 on 2022-07-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_alter_article_article_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_id",
            field=models.UUIDField(
                default="b58ff45c845b45ca81102ce65454dde7",
                editable=False,
                unique=True,
            ),
        ),
    ]
