# Generated by Django 4.0.6 on 2022-08-04 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_articlebookmark_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlebookmark",
            name="article",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="articles.article",
            ),
        ),
    ]
