# Generated by Django 4.0.6 on 2022-07-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_alter_article_article_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_id",
            field=models.UUIDField(
                default="b9a775dbc65e4291afb1b32e1260ff11",
                editable=False,
                unique=True,
            ),
        ),
    ]
