# Generated by Django 4.1 on 2022-08-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0009_alter_articlebookmark_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="reading_time",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
