# Generated by Django 4.1 on 2022-08-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0010_article_reading_time"),
        ("articles", "0010_articleratings"),
    ]

    operations = []
