# Generated by Django 4.1 on 2022-08-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0010_article_reading_time"),
        ("articles", "0011_remove_articlecomment_highlight_end_and_more"),
    ]

    operations = []
