# Generated by Django 4.1 on 2022-08-08 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "articles",
            "0012_remove_article_favourited_article_favourite_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="favourite",
            field=models.ManyToManyField(
                blank=True,
                related_name="favourite",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="unfavourite",
            field=models.ManyToManyField(
                blank=True,
                related_name="unfavourite",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
