# Generated by Django 4.1 on 2022-08-08 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0010_articleratings"),
        ("articles", "0012_merge_20220805_1215"),
    ]

    operations = []
