# Generated by Django 4.1 on 2022-08-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "articles",
            "0011_merge_0010_article_reading_time_0010_articleratings",
        ),
        (
            "articles",
            "0013_merge_0010_articleratings_0012_merge_20220805_1215",
        ),
    ]

    operations = []
