# Generated by Django 4.1 on 2022-08-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0013_alter_article_favourite_alter_article_unfavourite"),
        ("articles", "0014_merge_20220808_0856"),
    ]

    operations = []
