# Generated by Django 4.1 on 2022-08-11 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0013_alter_article_favourite_alter_article_unfavourite"),
        ("articles", "0015_articlehighlight"),
    ]

    operations = []
