# Generated by Django 4.1 on 2022-08-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0015_merge_20220811_0856"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="views",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
