# Generated by Django 4.1 on 2022-08-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0016_merge_20220811_0719"),
        ("articles", "0016_rename_comment_id_articlecomment_id_and_more"),
    ]

    operations = []
