# Generated by Django 4.1 on 2022-08-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0016_article_views"),
        ("articles", "0017_merge_20220811_0726"),
    ]

    operations = []
