# Generated by Django 4.1 on 2022-08-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0018_merge_0016_article_views_0017_merge_20220811_0726"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="views",
        ),
    ]
