version: 2.1
orbs:
  python: circleci/python@2.0.3

executors:
  my_executor:
      docker:
        - image: cimg/python:3.10
          environment: 
            SECRET_KEY: circlecisecretkey
        - image: cimg/base:2021.04
          environment:
            DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
        - image: circleci/postgres:9.6.2
          environment:
            POSTGRES_USER: chris
            POSTGRES_DB: circle_test

jobs:
  build_and_test:
    executor: my_executor
    steps:
      - checkout
      - python/install-packages:
          args: --dev
          pkg-manager: pipenv
      - run:
          command: |
            pipenv run pytest 
          name: Test it
workflows:
  main:
    jobs:
      - build_and_test