version: 2.1
orbs:
  python: circleci/python@2.0.3

executors:
  my_executor:
      docker:
        - image: cimg/python:3.10
          environment:
            SECRET_KEY: circlecisecretkey
            DATABASE_URL: postgresql://circle:password@localhost/circle_test?sslmode=disable
            ENV_NAME: local
        - image: circleci/postgres:latest
          environment:
            POSTGRES_USER: circle
            POSTGRES_PASSWORD: password
            POSTGRES_DB: circle_test

jobs:
  build_and_test:
    executor: my_executor
    steps:
      - checkout
      - python/install-packages:
          args: --dev
          pkg-manager: pipenv
      - run:
          command: |
            pipenv run pytest
          name: Test it
workflows:
  main:
    jobs:
      - build_and_test
