# Generated by Django 4.0.6 on 2022-07-07 07:22

import hashid_field.field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=hashid_field.field.HashidAutoField(
                alphabet="0123456789abcdef",
                min_length=7,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
