# Generated by Django 4.0.6 on 2022-07-07 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
