# Generated by Django 4.0.6 on 2022-07-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
